# Generated by Django 4.2 on 2023-11-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='loans',
            name='name',
        ),
        migrations.AddField(
            model_name='loans',
            name='name_and_last_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loans',
            name='requested_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
